import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  outDir: 'dist',
  sourcemap: true,
  clean: true,
  format: ['esm'],
  dts: true,
  splitting: false,
  target: 'es2022',
  platform: 'node',
  bundle: true,
  treeshake: false,
  external: [
    // Node.js built-in modules
    'node:*',
    'fs',
    'path',
    'os',
    'crypto',
    'stream',
    'http',
    'https',
    'util',
    'url',
    'events',
    'zlib',
    'buffer',
    'assert',
    'tty',
    'punycode',
    'querystring',
    'string_decoder',
    'child_process',
    'worker_threads',
    'net',
    'tls',
    
    // NPM packages
    'dotenv',
    '@reflink/reflink',
    '@node-llama-cpp',
    'agentkeepalive',
    'safe-buffer',
    'base-x',
    'bs58',
    'borsh',
    '@solana/buffer-layout',
    'amqplib',
    '@elizaos/core',
    '@solana/web3.js',
    '@coral-xyz/anchor',
    '@solana/spl-token',
    'bignumber.js',
    'pumpdotfun-sdk',
    'axios',
    'tweetnacl',
    'node-cache',
    'crypto-js',
    'zod'
  ]
});
