FROM node:23.5.0-bookworm AS base

WORKDIR /opt/app

RUN npm install -g pnpm@9.15.2
RUN apt-get update && \
    apt-get install build-essential -y

COPY . .

# node_modules/, data/ will be mounted from host
CMD [ "pnpm", "start:full" ]
