import { TwitterConfig } from '@elizaos/client-twitter';

// twitter config
// telegram config
export type CharacterConfigSecrets = {
  TELEGRAM_BOT_TOKEN?: string;
  // this will generated by system, when connect to the telegram bot
  TELEGRAM_BOT_USERNAME?: string;
} & TwitterConfig;
