version: '3.8'

services:
  phala:
    image: phalanetwork/tappd-simulator:0.0.6
    container_name: phala-tee-simulator
    restart: always
    ports:
      - "8090:8090"
    networks: 
    - core_local

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_REPL_SET_NAME=rs0
    command: >
      bash -c "
        mongod --replSet rs0 --bind_ip 0.0.0.0 --bind_ip_all &
        sleep 5 &&
        mongo mongodb:27017 --eval 'rs.initiate()' &&
        wait"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "rs.status()"]
      start_period: 5s
      interval: 5s
      retries: 10
      timeout: 30s
    networks: 
    - core_local

  core: 
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    # vscode auto export ports
    # ports:
    #   - "8080:8080"
    #   - "3000:3000"
    volumes:
      - core_data:/app/node_modules
    environment:
      - WALLET_SERVICE_ENDPOINT=http://wallet:8080
      - WALLET_SERVICE_SECRET_TOKEN="EDIT THIS"
    networks: 
    - core_local
    depends_on:
      - wallet
      - mongodb
    command: ["sleep", "10000000"]

  agent: 
    image: xnomadai/debug-client:0.0.1
    command: ["/bin/bash", "-c", "pnpm run dev --host"]
    ports:
      - "5173:5173"
    networks: 
    - core_local

  wallet: 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: xnomadai/core-wallet:0.1.2
    environment:
      - WALLET_SERVICE_SECRET_TOKEN="EDIT THIS"
      - TEE_MODE=DOCKER
    networks: 
    - core_local
    depends_on:
      - phala

networks:
  core_local:
    driver: bridge

volumes:
  mongo_data:
    driver: local
  core_data:
    driver: local
